export const DEFECT_TYPES = [
  "Abrasion mark",
  "Dyeing / Knitting / Weaving Barre",
  "Crease / Pleat mark",
  "Dye stains",
  "Embroidery Broken",
  "Embroidery placement",
  "Embroidery wrong pattern",
  "Filling bar / weaving bar",
  "Hole",
  "Irregular Weaving / Knitting",
  "Jacquard",
  "Joint piece / splice",
  "Knot",
  "Loose warp / weft",
  "Mending mark",
  "Neps / slub",
  "Oil stain",
  "Pen mark",
  "Printing stain",
  "Dirty stain",
  "Water mark",
  "Printing missing",
  "Printing tilted",
  "Printing wrong",
  "Printing uneven",
  "Selvage wavy",
  "Selvage broken",
  "Selvage tight",
  "Selvage slack",
  "Uneven dye",
  "Yarn foreign / color",
  "Yarn pulled",
  "Yarn missing",
  "Coarse yarn",
  "Double Yarn",
  "Other"
];

export const DETAILED_RESULT_CHECKPOINTS = [
  'Color Conformity',
  'Face to Face / Edge to Edge',
  'Roll to Roll Variation',
  'Width',
  'Bow / Skew',
  'GSM',
  'Roll Length',
  'Joint Pieces',
  'Handfeel',
  'General Conformity',
] as const;

export const DETAILED_RESULT_OPTIONS = ['Pass', 'Fail', 'N/A'] as const;
